const CONSTS = {
  // action types
  LOAD_PROJECT: "LOAD_PROJECT",
  SET_ACTIVE_ID: "SET_ACTIVE_ID",
  SET_ACTIVE_FEATURE: "SET_ACTIVE_FEATURE",
  NONE_FEATURE: "NONE_FEATURE",
  JUNCTION_FEATURE: "JUNCTION_FEATURE",
  OUTFALL_FEATURE: "OUTFALL_FEATURE",
  CONDUIT_FEATURE: "CONDUIT_FEATURE",
  SUBCATCHMENT_FEATURE: "SUBCATCHMENT_FEATURE",

  // strings
  JUNCTION_GRAPH_ID_PREFIX: "JUNCTION-GRAPH-",
  JUNCTION_ID_PREFIX: "JUNCTION-",
  OUTFALL_GRAPH_ID_PREFIX: "OUTFALL-GRAPH-",
  OUTFALL_ID_PREFIX: "OUTFALL-",
  CONDUIT_GRAPH_ID_PREFIX: "CONDUIT-GRAPH-",
  CONDUIT_ID_PREFIX: "CONDUIT-",
  SUBCATCHMENT_GRAPH_ID_PREFIX: "SUBCATCHMENT-GRAPH-",
  SUBCATCHMENT_ID_PREFIX: "SUBCATCHMENT-",

  // canvas
  SELECTED_SCALE: {x: 1.5, y: 1.5},
  SELECTED_STROKE_WIDTH: 2,
  SELECTED_STROKE_COLOR: "red",
  SELECTED_FILL_COLOR: "red",
  DEFAULT_SCALE: {x: 1, y: 1},
  DEFAULT_STROKE_WIDTH: 1,
  DEFAULT_STROKE_COLOR: "black",
  DEFAULT_FILL_COLOR: "black"
};

export default CONSTS;
