const CONSTS = {
  // common string
  EMPTY_STRING: "",

  // action types
  LOAD_PROJECT: "LOAD_PROJECT",
  SET_ACTIVE_ITEM: "SET_ACTIVE_ITEM",
  EDIT_ACTIVE_ITEM: "EDIT_ACTIVE_ITEM",
  SET_ACTIVE_FEATURE: "SET_ACTIVE_FEATURE",
  TOGGLE_PIN_RIGHT_PANE: "TOGGLE_PIN_RIGHT_PANE",
  CLOSE_RIGHT_PANE: "CLOSE_RIGHT_PANE",
  UPDATE_LIST_FILTER: "UPDATE_LIST_FILTER",

  // active feature
  NONE_FEATURE: "NONE_FEATURE",
  JUNCTION_FEATURE: "JUNCTION_FEATURE",
  OUTFALL_FEATURE: "OUTFALL_FEATURE",
  DIVIDER_FEATURE: "DIVIDER_FEATURE",
  STORAGE_FEATURE: "STORAGE_FEATURE",
  CONDUIT_FEATURE: "CONDUIT_FEATURE",
  PUMP_FEATURE: "PUMP_FEATURE",
  ORIFICE_FEATURE: "ORIFICE_FEATURE",
  WEIR_FEATURE: "WEIR_FEATURE",
  OUTLET_FEATURE: "OUTLET_FEATURE",
  SUBCATCHMENT_FEATURE: "SUBCATCHMENT_FEATURE",

  // strings
  JUNCTION_GRAPH_ID_PREFIX: "JUNCTION-GRAPH-",
  JUNCTION_ID_PREFIX: "JUNCTION-",
  OUTFALL_GRAPH_ID_PREFIX: "OUTFALL-GRAPH-",
  OUTFALL_ID_PREFIX: "OUTFALL-",
  DIVIDER_GRAPH_ID_PREFIX: "DIVIDER-GRAPH-",
  DIVIDER_ID_PREFIX: "DIVIDER-",
  STORAGE_GRAPH_ID_PREFIX: "STORAGE-GRAPH-",
  STORAGE_ID_PREFIX: "STORAGE-",
  CONDUIT_GRAPH_ID_PREFIX: "CONDUIT-GRAPH-",
  CONDUIT_ID_PREFIX: "CONDUIT-",
  PUMP_GRAPH_ID_PREFIX: "PUMP-GRAPH-",
  PUMP_ID_PREFIX: "PUMP-",
  ORIFICE_GRAPH_ID_PREFIX: "ORIFICE-GRAPH-",
  ORIFICE_ID_PREFIX: "ORIFICE-",
  WEIR_ID_PREFIX: "WEIR-",
  WEIR_GRAPH_ID_PREFIX: "WEIR-GRAPH-",
  OUTLET_ID_PREFIX: "OUTLET-",
  OUTLET_GRAPH_ID_PREFIX: "OUTLET-GRAPH-",
  SUBCATCHMENT_GRAPH_ID_PREFIX: "SUBCATCHMENT-GRAPH-",
  SUBCATCHMENT_ID_PREFIX: "SUBCATCHMENT-",

  // canvas
  SELECTED_SCALE: {x: 1.5, y: 1.5},
  SELECTED_STROKE_WIDTH: 2,
  SELECTED_STROKE_COLOR: "red",
  SELECTED_FILL_COLOR: "red",
  DEFAULT_SCALE: {x: 1, y: 1},
  DEFAULT_STROKE_WIDTH: 1,
  DEFAULT_STROKE_COLOR: "black",
  DEFAULT_FILL_COLOR: "black"
};

export default CONSTS;
